### ISSUE TITLE
[META] Use "ZURB" instead of "Zurb" (or "zurb") consistently everywhere in UI text.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/zurb_foundation_5#3]
The official, trademarked company name is "ZURB":

http://zurb.com
https://en.wikipedia.org/wiki/ZURB

Let's make sure that we use the capitalized form consistently everywhere (besides code and filenames of course).
- [x] #1 | Pretty name in zurb_foundation_5.info - this issue solved the text in the name in the themes list (`admin/appearance`)
- [ ] Wrong capitalization in the theme description text in the themes list (`admin/appearance`):

![backdrop-contrib_themes-zurb_foundation_5-wrong_capitalization_in_theme_description](https://cloud.githubusercontent.com/assets/2423362/13030990/91a7ac18-d310-11e5-81b7-c65c585067f6.png)

...that text is once again inside the .info file.
- [ ] Non-pretty name in the "Available updates" page (`admin/reports/updates`):

![backdrop-contrib_themes-zurb_foundation_5-non_pretty_name_in_available_updates_page](https://cloud.githubusercontent.com/assets/2423362/13030992/a3d2f442-d310-11e5-826a-4fcdbb38ac32.png)

...not sure why this happens. I thought this was automatically picked up from the .info file which was corrected in v1.3.0. Core bug perhaps??
- [ ] 6 occurrences of "Zurb" in the README.md file.
- [ ] Code comments perhaps?
